from database import SessionLocal
from models import SujetPFE

sujets = [
    dict(reference="PFE-2026-01", annee=2026,
         titre="Unité automatique de marquage manchons et application de CAF",
         description="Ce projet a pour objectif de concevoir une unité de marquage automatique dédiée aux manchons, intégrant également l'application d'un verni de protection (CAF) pour garantir la durabilité des marquages. Le stagiaire étudiera les solutions technologiques possibles afin de concevoir un dispositif automatique qui concrétisera cette idée.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en mécanique ou équivalent. Bonne maîtrise des outils CAO (Catia ou Solidworks). Des connaissances en automatisme et en pneumatique sera un atout",
         environnement_technique="CAO, Électrotechnique, TIA Portal",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="Nabil AMARA", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-02", annee=2026,
         titre="Étude Énergétique du Chauffage par Induction des Moules",
         description="Ce projet consiste à analyser la rentabilité énergétique et économique du chauffage des moules par induction. L'objectif est d'évaluer l'efficacité de cette méthode de chauffage par rapport à celle par résistance. Le stagiaire examinera les coûts d'installation, de fonctionnement et d'entretien, ainsi que les économies d'énergie potentielles.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en mécatronique ou énergétique. Bonne maîtrise des outils CAO (Catia ou SolidWorks). Thermodynamique et connaissance des matériaux sera un atout",
         environnement_technique="CAO, Électrotechnique, TIA Portal",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="Nabil AMARA", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-03", annee=2026,
         titre="Station automatique d'assemblage du verrou Rack",
         description="Ce projet a pour objectif de concevoir une station automatisée pour le montage des verrous Rack, intégrant une séquence d'assemblage d'une dizaine de composants afin d'optimiser la cadence et la précision de montage.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en mécanique ou équivalent. Bonne maîtrise des outils CAO (Catia ou Solidworks). Des connaissances en automatisme et en pneumatique sera un atout",
         environnement_technique="CAO, Électrotechnique, TIA Portal",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="Nabil AMARA", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-04", annee=2026,
         titre="Automatisation du montage des garnitures de colliers",
         description="Ce projet vise à concevoir une machine automatisée pour assembler les garnitures des colliers, afin d'améliorer la productivité, l'ergonomie et la qualité. Le stagiaire étudiera les solutions technologiques intégrant positionnement, fixation et insertion, avec une flexibilité pour différents modèles.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en mécanique ou équivalent. Bonne maîtrise des outils CAO (Catia ou SolidWorks). Des connaissances en automatisme et en pneumatique sera un atout",
         environnement_technique="CAO, Électrotechnique, TIA Portal",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="Nabil AMARA", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-05", annee=2026,
         titre="Automatisation du soudeuse ABS901",
         description="Ce projet consiste à automatiser les opérations de soudure (soudeuse par point ABS901) afin d'améliorer la productivité, la précision et la sécurité, tout en réduisant les coûts et les erreurs humaines. L'automatisation intégrera le test de déboutonnage et le suivi en temps réel des paramètres de soudure.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en mécatronique ou équivalent. Bonne maîtrise des outils CAO (Catia ou SolidWorks). Des connaissances en automatisme et en pneumatique sera un atout",
         environnement_technique="CAO, Électrotechnique, TIA Portal",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="Nabil AMARA", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-06", annee=2026,
         titre="Analyse de cycle de vie et Eco-conception",
         description="Afin de renforcer la démarche d'éco-conception et réduire l'empreinte carbone des produits, la méthode d'Analyse du Cycle de Vie (ACV) sera appliquée conformément aux normes et référentiels sectoriels. Le stagiaire analysera les normes et outils, collectera les données, réalisera les calculs d'empreinte carbone, proposera des pistes de réduction et assurera la documentation et l'archivage dans les bases dédiées.",
         profil_requis="Ingénieur / Master",
         competences_requises="Niveau terminal de cycle d'ingénieur en mécanique/matériaux/énergie/environnement ou équivalent. Connaissance de la méthodologie d'Analyse de Cycle de Vie. Une expérience avec des logiciels ACV est un plus. Maîtrise de Microsoft Excel et de PowerPoint",
         environnement_technique="Logiciel ACV : Askor, Bases de données : Ecoinvent, Normes : ISO14040, ISO14044, ISO14067",
         nombre_stagiaires=1, duree_stage="4 à 6 mois",
         responsable_stage="Mazen JERJIR / Iadh HAMILA", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-07", annee=2026,
         titre="Développement de tableaux de bord BI pour le suivi des indicateurs de performance industrielle",
         description="Contribuer au développement et à la mise en place de tableaux de bord BI permettant le suivi et l'analyse des indicateurs clés liés à la production, l'efficience, la qualité et la supply chain. L'objectif est d'améliorer la visibilité des performances opérationnelles et d'optimiser la prise de décision grâce à des outils analytiques fiables et automatisés.",
         profil_requis="Ingénieur",
         competences_requises="Capacité d'apprentissage rapide, Capacité d'analyse et réflexion. Le candidat devra disposer d'un bon degré d'autonomie et d'être capable de travailler avec un degré minimal de supervision.",
         environnement_technique="Power BI, Connexion et Intégration des Données, ETL",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="Majdi KAOUECH", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-08", annee=2026,
         titre="Etude et développement d'un système de traçabilité numérique et de détection par vision en temps réels les risque de sécurité de la presse 'SUNRISE'",
         description="Ce projet a pour objectif principal de définir un cahier des charges, d'étudier les solutions actuelles et d'intégrer un système numérique innovant permettant de : régler et contrôler avec précision la course du piston de la presse ; enregistrer automatiquement les paramètres de fabrication (course et pression) sous forme de programmes spécifiques ; créer un historique détaillé, mensuel et annuel, des opérations de pliage ou d'emboutissage pour chaque OF ; mettre en place un système de sécurité des opérateurs basé sur la technologie de vision pour une protection optimale.",
         profil_requis="Ingénieur",
         competences_requises="Capacité d'apprentissage rapide, Capacité d'analyse et réflexion. Le candidat devra disposer d'un bon degré d'autonomie et d'être capable de travailler avec un degré minimal de supervision.",
         environnement_technique="Connaissances Python et automatisme, Raspberry Pi, Roboflow / Yolo, Open CV",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="Majdi KAOUECH", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-09", annee=2026,
         titre="Etude et développement d'un système vision pour sécuriser la machine de confection des manchons aéronautiques",
         description="Les manchons sont destinés au raccordement entre conduits d'air aéronautiques. Ils ont des diamètres qui varient entre 16 mm et 350 mm. Afin d'améliorer les conditions ergonomiques et de sécurité de l'opération de fabrication de ces manchons, le candidat aura à sa charge le développement et la mise en place d'un système de vision et de paramétrage de la machine de confection en temps réels.",
         profil_requis="Ingénieur",
         competences_requises="Capacité d'apprentissage rapide, Capacité d'analyse et réflexion. Le candidat devra disposer d'un bon degré d'autonomie et d'être capable de travailler avec un degré minimal de supervision.",
         environnement_technique="Connaissances Python et automatisme, Traitement d'image, Open CV, Raspberry Pi, Roboflow / Yolov",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="Majdi KAOUECH", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-10", annee=2026,
         titre="Etude et développement d'un système vision pour sécuriser la machine de poinçonnage des produits aéronautiques",
         description="Afin d'améliorer les conditions de sécurité de l'opération de poinçonnage des tôles fines pour les produits aéronautiques, le candidat aura à sa charge le développement et la mise en place d'un système vision de reconnaissance des gestes manuelles pour sécuriser la machine de poinçonnage en temps réels.",
         profil_requis="Ingénieur",
         competences_requises="Capacité d'apprentissage rapide, Capacité d'analyse et réflexion. Le candidat devra disposer d'un bon degré d'autonomie et d'être capable de travailler avec un degré minimal de supervision.",
         environnement_technique="Connaissances Python et automatisme, Traitement d'image, Open CV, Raspberry Pi, Roboflow / Yolov",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="Majdi KAOUECH", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-11", annee=2026,
         titre="Smart Applications Catalogue",
         description="L'idée est d'avoir une solution qui catalogue les applications crées dans les sites Hutchinson. Elle donne la possibilité aux employés de consulter, à l'aide d'une IA, les projets réalisés. Avoir la possibilité de recommander et stocker les données et d'apprendre à améliorer la qualité des développements par rapport aux demandes client.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en informatique ou équivalent. Bonne maîtrise de python. Des connaissances en intelligence artificielle. Des connaissances en React JS sera un atout",
         environnement_technique="React Js, Python, AI",
         nombre_stagiaires=2, duree_stage="6 mois",
         responsable_stage="Mouez BAHRI", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-12", annee=2026,
         titre="Multi Agent Dynamic System",
         description="Il consiste d'un système multi-agents AI avec un agent orchestrateur. Il pourra, par exemple, faciliter la délivrance de l'informations relative à la société et l'intégration du personnel ainsi que d'autres fonctionnalités. L'idée est de faire un modèle standard, avec les bonnes données. Il sera capable de fonctionner et d'apprendre.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en informatique ou équivalent. Bonne maîtrise de python. Des connaissances en intelligence artificielle",
         environnement_technique="Python, AI",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="Mouez BAHRI", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-13", annee=2026,
         titre="Model AI de prédiction pour le service Supply Chain",
         description="Construire un model de prédiction avec l'AI pour les données du Supply Chain venue de l'ERP. Aide décisionnelle par rapport des paterne de données.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en informatique ou équivalent. Bonne maîtrise de python. Des connaissances en intelligence artificielle. Des connaissances en React JS sera un atout",
         environnement_technique="Python, AI",
         nombre_stagiaires=1, duree_stage="4 - 6 mois",
         responsable_stage="Anis BOUZRARA", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-14", annee=2026,
         titre="Développement d'une version Web pour l'outil « BDT DCP » (incluant les fonctionnalités MCT)",
         description="L'outil actuel « BDT DCP » est une application WPF en C# permettant de tester et valider l'équipement Display Control Panel (DCP). Il offre des fonctionnalités telles que l'exécution de scénarios de test, la collecte des résultats et la génération de rapports PDF. Ce projet consiste à concevoir et développer une version Web moderne de cet outil, accessible via un navigateur, tout en intégrant les fonctionnalités essentielles de maintenance et configuration (MCT).",
         profil_requis="Ingénieur en Informatique / Développement Web",
         competences_requises="Maîtrise des technologies React.js et JavaScript/TypeScript. Connaissance des API REST et intégration avec systèmes existants. Familiarité avec Git/GitHub pour la gestion de version. Notions de Docker pour la conteneurisation. Bonne compréhension des concepts UI/UX pour une interface ergonomique",
         environnement_technique="React.js (JavaScript ou TypeScript), Git, GitHub, Docker, NPM ou Bun",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="MAHMOUDI Ahmed & KORTOBA Faten", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-15", annee=2026,
         titre="Évolution de l'outil Nexus Console pour la création des ponts de communication Hardware/Web Apps",
         description="L'outil Nexus Console est actuellement une application WPF en C# utilisée pour gérer la communication entre les équipements électroniques et les applications web locales. L'objectif est d'ajouter de nouveaux ponts de communication pour intégrer de nouveaux produits et leurs applications Web.",
         profil_requis="Ingénieur en Informatique / Développement Logiciel",
         competences_requises="Maîtrise du développement C# (.NET). Connaissance des protocoles de communication hardware (série, TCP/IP, etc.). Développement et sécurisation d'API HTTP. Familiarité avec Git/GitHub pour la gestion de version. Bonne compréhension des architectures client-serveur",
         environnement_technique="C#, WPF, .NetFramework",
         nombre_stagiaires=1, duree_stage="4 - 5 mois",
         responsable_stage="KORTOBA Faten", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-16", annee=2026,
         titre="Méthodologie de modélisation et de dimensionnement des conduits d'air aéronautiques par simulation CFD – Perte de Charges & Efficacité Thermique",
         description="Pour donner suite à des exigences clients élevées, les conduits d'air aéronautiques doivent répondre à plusieurs critères tout en assurant la performance optimale du système d'aération des avions. Modélisation et optimisation des conduits d'air aéronautiques avec les logiciels FloMaster et StarCCM+, et Benchmark des résultats du calcul CFD avec des méthodes analytiques.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en mécanique. Bonne maîtrise de la mécanique des fluides et des techniques de transfert de chaleur. Capacité d'apprentissage rapide, Capacité d'analyse et réflexion. Le candidat devra disposer d'un bon degré d'autonomie et d'être capable de travailler avec un degré minimal de supervision",
         environnement_technique="Ansys, StarCCM+, OpenFOAM",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="Wafa BEN ALI", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-17", annee=2026,
         titre="Sécurisation du Processus par Vérification d'Identité Produit (Vision Industrielle) - Reconnaissance de texte",
         description="L'idée est d'automatiser la lecture (reconnaissance de texte) des codes ou références critiques inscrits sur les tôles ou les pièces. Ce contrôle automatique permet de garantir la conformité et l'identité des produits avant de procéder aux opérations de marquages. Le stagiaire aura pour mission d'étudier les différentes solutions techniques envisageables, puis de développer et mettre en œuvre celle qui sera retenue.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en mécatronique ou équivalent. Bonne maîtrise de l'environnement Linux. Des connaissances en systèmes embarqués et automatisme",
         environnement_technique="Python, Raspberry, OCR-OpenCV",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="Chames HAJ AYED", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-18", annee=2026,
         titre="Sécurisation du Processus par Vérification d'Identité Produit (Vision Industrielle) - Détection de colle fluorescente",
         description="L'objectif est d'automatiser l'inspection et le contrôle de conformité des produits en se basant sur la détection de la présence de colle ou de substance fluorescente. Le stagiaire aura pour mission d'étudier les différentes solutions techniques (choix des composants optiques, mise au point de l'éclairage UV), puis de développer et mettre en œuvre l'algorithme de traitement d'image pour détecter et valider la présence de cette substance fluorescente.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en mécatronique, électronique, informatique industrielle ou équivalent. Bonne maîtrise de l'environnement Linux. Des connaissances en systèmes embarqués et automatisme.",
         environnement_technique="Python, Raspberry, OpenCV",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="Chames HAJ AYED", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-19", annee=2026,
         titre="Sécurisation du Processus par Vérification d'Identité Produit (Vision Industrielle) - Supervision de parc IoT",
         description="On souhaite mettre en place un système centralisé et fiable pour surveiller, gérer et collecter les données de son parc de dispositifs IoT industriels (principalement basés sur Raspberry Pi) déployés sur le réseau local. Le stagiaire sera responsable du projet dans son intégralité, de la phase de conception à la mise en service du prototype fonctionnel.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en Informatique, développement Logiciel ou similaire. Langages : Maîtrise avancée de Python et expérience significative avec le framework Django. Des connaissances en systèmes embarqués et automatisme.",
         environnement_technique="Django, SQL/MYSQL, API RESTful",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="Chames HAJ AYED", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-20", annee=2026,
         titre="Optimisation de la performance service qualité fournisseur par la mise en place d'outils de pilotage et d'amélioration continue",
         description="L'objectif est d'améliorer l'organisation et la performance du service qualité fournisseur au sein du site industriel. L'approche adoptée repose sur l'optimisation des flux, la réduction des gaspillages identifiés (mudas), et l'implémentation d'outils adaptés à la gestion et au suivi des activités. Le projet permettra une meilleure maîtrise des processus fournisseurs, une anticipation des non-conformités, et une amélioration continue de la performance globale du service.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en mécanique, génie industriel ou équivalent. Bonne maîtrise des outils bureautiques et de visualisation (Excel avancé, Power BI). Des connaissances des outils qualité (Ishikawa, Pareto, PDCA..) et des outils lean (VSM, 5S, Kaizen..)",
         environnement_technique="Excel avancé / Power BI, Outils qualité, Outils Lean",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="LABIDI Fatma", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-21", annee=2026,
         titre="Optimisation de la gestion des PPAP et de la requalification des composants fournisseurs",
         description="L'objectif est d'améliorer l'efficacité et la fiabilité du processus de gestion des PPAP (Production Part Approval Process) ainsi que de la requalification des composants fournisseurs, tout en renforçant le suivi des indicateurs qualité. Le projet vise à assurer une meilleure maîtrise des processus liés aux fournisseurs, anticiper les risques de non-conformité et favoriser une amélioration continue de la performance globale du service qualité.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en mécanique, génie industriel ou équivalent. Bonne maîtrise des outils bureautiques et de visualisation (Excel avancé, Power BI). Des connaissances des outils qualité (Ishikawa, Pareto, PDCA..) et de la démarche APQP et processus PPAP.",
         environnement_technique="Excel avancé / Power BI, Outils qualité, Processus PPAP",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="LABIDI Fatma", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-22", annee=2026,
         titre="Mise en place d'un système interne d'étalonnage des instruments de température",
         description="Dans le but de renforcer la fiabilité de notre production et d'assurer une qualité constante de nos produits, nous envisageons la mise en place d'un système d'étalonnage interne des instruments de mesure de la température. Le stagiaire sera chargé de développer les procédures et les instructions techniques relatives à l'étalonnage de cette grandeur, conformément aux exigences normatives et aux bonnes pratiques métrologiques. Calculer le bilan d'incertitude de mesure selon la méthode GUM.",
         profil_requis="Ingénieur ou équivalent",
         competences_requises="Niveau terminal de cycle d'ingénieur IMI ou équivalent en métrologie. Bonne maîtrise des outils qualité. Des connaissances des normes ISO17025/LABGTA08/FD X07-028",
         environnement_technique="Métrologie, Qualité",
         nombre_stagiaires=1, duree_stage="6 mois",
         responsable_stage="HEDHLI Riadh", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-23", annee=2026,
         titre="Optimisation du processus de traitement QRQC",
         description="Réduire le temps de traitement et améliorer l'efficacité des actions correctives. Standardiser les réactions face aux défauts récurrents via des fiches visuelles et simples basé sur des études R-FMEA.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en industriel / mécanique ou équivalent. Bonne maîtrise des outils Qualité",
         environnement_technique="Outils qualité",
         nombre_stagiaires=1, duree_stage="4 mois",
         responsable_stage="KAMMOUN Tarek", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-24", annee=2026,
         titre="Digitalisation et optimisation du processus Lessons Learned (LLC)",
         description="Mettre en place une plateforme collaborative pour centraliser et structurer les Lessons Learned afin de faciliter leur exploitation. Réduire les pertes d'information et améliorer la réutilisation des bonnes pratiques dans les projets futurs. Définir une structure standard (catégorisation, criticité, tags) et automatiser le reporting via un tableau de bord.",
         profil_requis="Ingénieur",
         competences_requises="Niveau terminal de cycle d'ingénieur en industriel / mécanique / informatique industrielle ou équivalent. Bonne maîtrise des outils qualité (QRQC, AMDEC) et notions en digitalisation (Power BI, SharePoint, Power Apps)",
         environnement_technique="Outils qualité, Outils digitaux",
         nombre_stagiaires=1, duree_stage="4 à 6 mois",
         responsable_stage="KAMMOUN Tarek", email_contact="stages-sousse@hutchinson.com"),

    dict(reference="PFE-2026-25", annee=2026,
         titre="Évaluation des risques chimiques et optimisation des mesures de sécurité",
         description="Dans le cadre du renforcement de la sécurité chimique et de la conformité réglementaire, nous souhaitons accueillir un(e) stagiaire pour : analyser les risques liés aux produits chimiques présents dans les ateliers et services ; mettre en place une base de données structurée pour l'évaluation des risques chimiques (classification, dangerosité, quantités, zones d'utilisation) ; proposer un plan d'actions visant à améliorer les mesures de prévention et de protection existantes ; contribuer à la mise en conformité avec la réglementation tunisienne et les standards internes HSE.",
         profil_requis="Licence, Ingénieur ou Master",
         competences_requises="Niveau terminal de cycle d'ingénieur / master / licence en chimie ou équivalent. Maîtrise des outils bureautiques (Excel, Word) et idéalement des bases de données. Capacité à analyser et synthétiser des informations techniques. Aptitude à travailler en autonomie et à communiquer efficacement.",
         environnement_technique="Les outils bureautiques, Bon niveau de Français, Niveau intermédiaire en Anglais",
         nombre_stagiaires=1, duree_stage="3 mois",
         responsable_stage="Itidel HAMDI", email_contact="stages-sousse@hutchinson.com"),
]

db = SessionLocal()
ajoutes = 0
ignores = 0
for s in sujets:
    existe = db.query(SujetPFE).filter(SujetPFE.reference == s["reference"]).first()
    if existe:
        ignores += 1
        continue
    db.add(SujetPFE(**s))
    ajoutes += 1

db.commit()
db.close()
print(f"{ajoutes} sujets ajoutés, {ignores} déjà existants (ignorés).")
